# Generated by Django 5.2.17 on 2026-09-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deletion_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_promotions",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="newsletter",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="user",
            name="sms_promotions",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="whatsapp_updates",
            field=models.BooleanField(default=True),
        ),
    ]
