# Generated by Django 6.1.1 on 2026-10-05 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckoutSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("allow_guest_checkout", models.BooleanField(default=True)),
                ("require_phone", models.BooleanField(default=True)),
                ("auto_confirm_orders", models.BooleanField(default=False)),
                ("whatsapp_fallback", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeliveryZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("region", models.CharField(max_length=128)),
                ("fee_kes", models.DecimalField(decimal_places=2, max_digits=10)),
                ("eta_text", models.CharField(max_length=64)),
                ("enabled", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="EtimsConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kra_pin", models.CharField(blank=True, max_length=16)),
                ("control_unit_id", models.CharField(blank=True, max_length=32)),
                ("device_serial", models.CharField(blank=True, max_length=32)),
                ("api_credentials", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EtimsSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(db_index=True, max_length=64)),
                ("invoice_number", models.CharField(blank=True, max_length=64)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("response", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="GeneralSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_name",
                    models.CharField(default="SokoFlow Commerce", max_length=200),
                ),
                ("tagline", models.CharField(blank=True, max_length=255)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=32)),
                ("address", models.TextField(blank=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("KES", "Kenyan Shilling"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                        ],
                        default="KES",
                        max_length=3,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        choices=[("Africa/Nairobi", "Africa/Nairobi"), ("UTC", "UTC")],
                        default="Africa/Nairobi",
                        max_length=64,
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        choices=[
                            ("DD/MM/YYYY", "DD/MM/YYYY"),
                            ("MM/DD/YYYY", "MM/DD/YYYY"),
                            ("YYYY-MM-DD", "ISO"),
                        ],
                        default="DD/MM/YYYY",
                        max_length=16,
                    ),
                ),
                (
                    "weight_unit",
                    models.CharField(
                        choices=[("kg", "Kilogram"), ("g", "Gram"), ("lb", "Pound")],
                        default="kg",
                        max_length=4,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IntegrationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Payments", "Payments"),
                            ("Messaging", "Messaging"),
                            ("Social app", "Social app"),
                            ("Social", "Social"),
                            ("Analytics", "Analytics"),
                        ],
                        max_length=16,
                    ),
                ),
                ("connected", models.BooleanField(default=False)),
                ("badge", models.CharField(blank=True, max_length=128)),
                ("description", models.TextField(blank=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="InventorySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("track_inventory", models.BooleanField(default=True)),
                ("low_stock_threshold", models.PositiveIntegerField(default=5)),
                ("allow_backorders", models.BooleanField(default=False)),
                ("hide_out_of_stock", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MpesaConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "environment",
                    models.CharField(
                        choices=[("sandbox", "Sandbox"), ("production", "Production")],
                        default="sandbox",
                        max_length=16,
                    ),
                ),
                ("consumer_key", models.TextField(blank=True)),
                ("consumer_secret", models.TextField(blank=True)),
                ("shortcode", models.CharField(blank=True, max_length=16)),
                ("passkey", models.TextField(blank=True)),
                ("callback_url", models.URLField(blank=True)),
                ("last_rotated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(db_index=True, max_length=64)),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("whatsapp", "WhatsApp")],
                        max_length=16,
                    ),
                ),
                ("recipient", models.CharField(max_length=255)),
                (
                    "order_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("success", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email_enabled", models.BooleanField(default=True)),
                ("whatsapp_enabled", models.BooleanField(default=True)),
                ("notify_on_new_order", models.BooleanField(default=True)),
                ("notify_on_payment", models.BooleanField(default=True)),
                ("notify_on_shipped", models.BooleanField(default=True)),
                ("notify_on_cancelled", models.BooleanField(default=True)),
                ("notify_on_low_stock", models.BooleanField(default=True)),
                ("notify_on_review", models.BooleanField(default=False)),
                ("admin_alert_email", models.EmailField(blank=True, max_length=254)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mpesa_enabled", models.BooleanField(default=True)),
                (
                    "min_amount_kes",
                    models.DecimalField(decimal_places=2, default=100, max_digits=10),
                ),
                (
                    "max_amount_kes",
                    models.DecimalField(
                        decimal_places=2, default=500000, max_digits=10
                    ),
                ),
                (
                    "transaction_fee_kes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("auto_capture", models.BooleanField(default=True)),
                ("auto_refund", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReviewSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviews_enabled", models.BooleanField(default=True)),
                ("require_verified_purchase", models.BooleanField(default=True)),
                ("auto_publish", models.BooleanField(default=False)),
                ("allow_photos", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SecuritySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_timeout_minutes", models.PositiveIntegerField(default=60)),
                ("require_2fa", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShippingProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("g4s", "G4S Kenya"),
                            ("fargo", "Fargo Courier"),
                            ("sendy", "Sendy"),
                            ("riders", "SokoFlow Riders"),
                        ],
                        max_length=16,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("enabled", models.BooleanField(default=False)),
                ("credentials", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="ShippingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("shipping_enabled", models.BooleanField(default=True)),
                (
                    "free_shipping_threshold_kes",
                    models.DecimalField(decimal_places=2, default=5000, max_digits=10),
                ),
                (
                    "default_delivery_fee_kes",
                    models.DecimalField(decimal_places=2, default=250, max_digits=10),
                ),
                ("local_pickup_enabled", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StoreSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("paused", "Paused"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("is_indexable", models.BooleanField(default=True)),
                ("paused_message", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaxSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("vat_enabled", models.BooleanField(default=True)),
                (
                    "vat_rate",
                    models.DecimalField(decimal_places=2, default=16, max_digits=5),
                ),
                ("prices_include_tax", models.BooleanField(default=True)),
                ("etims_enabled", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WhatsAppConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phone_number_id", models.CharField(blank=True, max_length=64)),
                ("waba_id", models.CharField(blank=True, max_length=64)),
                ("access_token", models.TextField(blank=True)),
                ("template_map", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LoginEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("device_label", models.CharField(blank=True, max_length=128)),
                ("location", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MpesaTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "merchant_request_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "checkout_request_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("phone", models.CharField(max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("result_code", models.CharField(blank=True, max_length=8)),
                ("result_desc", models.TextField(blank=True)),
                ("mpesa_receipt", models.CharField(blank=True, max_length=32)),
                ("raw_callback", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["order_id", "status"],
                        name="settings_mp_order_i_edd63c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SettingsAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section", models.CharField(db_index=True, max_length=64)),
                ("field_name", models.CharField(max_length=64)),
                ("before", models.TextField(blank=True)),
                ("after", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
    ]
