# Generated by Django 6.1.1 on 2026-10-03 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="review",
            name="catalog_rev_product_9831eb_idx",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
