# Generated by Django 6.1.1 on 2026-10-03 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_remove_review_catalog_rev_product_9831eb_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="channels",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Channels this discount runs on, e.g. ['Website', 'TikTok'].",
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who created this discount. Null for system jobs.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_discounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="expires_when_sold_out",
            field=models.BooleanField(
                default=False,
                help_text="Stop showing this discount on a product the moment its stock_quantity hits zero. Intended for clearance runs.",
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="is_automatic",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="When True, the discount is applied automatically to matching products without requiring a code. Required for clearance.",
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="is_clearance",
            field=models.BooleanField(
                default=False,
                help_text="Renders a 'Clearance' badge on the storefront instead of 'Deal'.",
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="source",
            field=models.CharField(
                choices=[
                    ("campaign", "Campaign"),
                    ("clearance", "Clearance"),
                    ("manual", "Manual"),
                    ("auto_slow_moving", "Auto (slow moving)"),
                ],
                db_index=True,
                default="manual",
                help_text="Why this discount exists — campaign, clearance, manual, or auto.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="status_override",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Auto (from dates)"),
                    ("Draft", "Draft"),
                    ("Paused", "Paused"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="tiktok_video",
            field=models.CharField(
                blank=True,
                help_text="Video URL or data URL for the scheduled TikTok post.",
                max_length=2000000,
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="discount",
            name="image",
            field=models.CharField(blank=True, max_length=2000000),
        ),
        migrations.AddIndex(
            model_name="discount",
            index=models.Index(
                fields=["is_automatic", "start_date"],
                name="catalog_dis_is_auto_e1cff7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="discount",
            index=models.Index(
                fields=["source", "-created_at"], name="catalog_dis_source_6a12bf_idx"
            ),
        ),
    ]
