# Generated by Django 6.1.1 on 2026-10-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_discount_channels_discount_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="promotion_type",
            field=models.CharField(
                choices=[
                    ("Percentage Discount", "Percentage Discount"),
                    ("Fixed Amount Discount", "Fixed Amount Discount"),
                    ("Sale Price", "Sale Price"),
                    ("Campaign", "Campaign"),
                    ("Free Shipping", "Free Shipping"),
                    ("Flash Sale", "Flash Sale"),
                    ("BOGO", "BOGO"),
                    ("Bundle Discount", "Bundle Discount"),
                    ("Tiered Discount", "Tiered Discount"),
                ],
                default="Percentage Discount",
                max_length=32,
            ),
        ),
    ]
