# Generated by Django 6.1.1 on 2026-10-02 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_name", models.CharField(max_length=150)),
                ("company", models.CharField(db_index=True, max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Manufacturer", "Manufacturer"),
                            ("Distributor", "Distributor"),
                            ("Wholesaler", "Wholesaler"),
                            ("Importer", "Importer"),
                            ("Retailer", "Retailer"),
                        ],
                        default="Distributor",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("country", models.CharField(default="Kenya", max_length=80)),
                ("county", models.CharField(blank=True, max_length=80)),
                ("city", models.CharField(blank=True, max_length=80)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("tax_pin", models.CharField(blank=True, max_length=40)),
                ("reg_number", models.CharField(blank=True, max_length=60)),
                ("payment_terms", models.CharField(blank=True, max_length=40)),
                ("payment_method", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        db_index=True,
                        default="Active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["company"],
                "indexes": [
                    models.Index(
                        fields=["status", "company"],
                        name="dashboard_s_status_82b5ba_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(db_index=True, max_length=40)),
                ("date", models.DateField()),
                ("items_count", models.PositiveIntegerField(default=0)),
                ("total_qty", models.PositiveIntegerField(default=0)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Paid", "Paid"),
                            ("Partial", "Partial"),
                            ("Unpaid", "Unpaid"),
                        ],
                        db_index=True,
                        default="Unpaid",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Received", "Received"),
                            ("Pending", "Pending"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="dashboard_suppliers.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["supplier", "-date"],
                        name="dashboard_s_supplie_09315f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SupplierActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("product_added", "Product added"),
                            ("purchase_recorded", "Purchase recorded"),
                            ("updated", "Updated"),
                        ],
                        max_length=32,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("user_label", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity",
                        to="dashboard_suppliers.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["supplier", "-created_at"],
                        name="dashboard_s_supplie_5997bc_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SupplierProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(db_index=True, max_length=64)),
                ("product_name", models.CharField(max_length=255)),
                ("product_sku", models.CharField(blank=True, max_length=80)),
                ("product_image", models.CharField(blank=True, max_length=500)),
                ("product_category", models.CharField(blank=True, max_length=120)),
                ("supplier_sku", models.CharField(blank=True, max_length=80)),
                (
                    "cost_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("min_order_qty", models.PositiveIntegerField(default=1)),
                ("lead_time_days", models.PositiveIntegerField(default=14)),
                (
                    "last_purchase_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("last_purchase_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_products",
                        to="dashboard_suppliers.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["supplier", "-created_at"],
                        name="dashboard_s_supplie_1813b1_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("supplier", "product_id"), name="uniq_supplier_product"
                    )
                ],
            },
        ),
    ]
