# Generated by Django 6.1.1 on 2026-10-04 00:00

import dashboard.whatsapp.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "checkout",
            "0005_paymentevent_reconciliationlog_payment_collected_by_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("waba_id", models.CharField(max_length=64, unique=True)),
                ("phone_number_id", models.CharField(max_length=64, unique=True)),
                (
                    "display_phone",
                    models.CharField(help_text="E.164, digits only", max_length=32),
                ),
                ("business_name", models.CharField(blank=True, max_length=128)),
                (
                    "access_token",
                    dashboard.whatsapp.models.EncryptedTextField(blank=True),
                ),
                (
                    "app_secret",
                    dashboard.whatsapp.models.EncryptedTextField(blank=True),
                ),
                ("verify_token", models.CharField(blank=True, max_length=128)),
                (
                    "quality_score",
                    models.CharField(
                        choices=[
                            ("GREEN", "Green"),
                            ("YELLOW", "Yellow"),
                            ("RED", "Red"),
                        ],
                        default="GREEN",
                        max_length=16,
                    ),
                ),
                ("messaging_limit", models.CharField(default="TIER_1K", max_length=32)),
                ("token_expires_at", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "WhatsApp Account",
                "verbose_name_plural": "WhatsApp Accounts",
            },
        ),
        migrations.CreateModel(
            name="WhatsAppContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wa_id",
                    models.CharField(
                        db_index=True,
                        help_text="E.164 digits, no '+' e.g. 254712345678",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("profile_name", models.CharField(blank=True, max_length=128)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "opt_in_status",
                    models.CharField(
                        choices=[
                            ("SUBSCRIBED", "Subscribed"),
                            ("UNSUBSCRIBED", "Unsubscribed"),
                        ],
                        default="SUBSCRIBED",
                        max_length=16,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("last_inbound_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whatsapp_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_inbound_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppCartSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cart_snapshot", models.JSONField(default=dict)),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("express", "Express"),
                            ("pickup", "Pickup"),
                        ],
                        default="standard",
                        max_length=16,
                    ),
                ),
                ("coupon_code", models.CharField(blank=True, max_length=32)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("READ", "Read"),
                            ("OPENED", "Opened"),
                            ("ORDERED", "Ordered"),
                            ("EXPIRED", "Expired"),
                            ("FAILED", "Failed"),
                        ],
                        default="CREATED",
                        max_length=16,
                    ),
                ),
                ("wa_message_id", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whatsapp_sessions",
                        to="checkout.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_cart_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cart_sessions",
                        to="whatsapp.whatsappcontact",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("PENDING", "Pending"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whatsapp_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="whatsapp.whatsappcontact",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wa_message_id",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("IN", "inbound"), ("OUT", "outbound")], max_length=3
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "text"),
                            ("template", "template"),
                            ("interactive", "interactive"),
                            ("image", "image"),
                            ("document", "document"),
                            ("audio", "audio"),
                            ("video", "video"),
                            ("sticker", "sticker"),
                            ("location", "location"),
                            ("contacts", "contacts"),
                            ("unknown", "unknown"),
                        ],
                        default="text",
                        max_length=16,
                    ),
                ),
                ("body", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("READ", "Read"),
                            ("FAILED", "Failed"),
                        ],
                        default="QUEUED",
                        max_length=16,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="whatsapp.whatsappconversation",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=128)),
                ("language", models.CharField(default="en", max_length=16)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("UTILITY", "Utility"),
                            ("MARKETING", "Marketing"),
                            ("AUTHENTICATION", "Authentication"),
                        ],
                        default="UTILITY",
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PAUSED", "Paused"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("GREEN", "Green"),
                            ("YELLOW", "Yellow"),
                            ("RED", "Red"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=16,
                    ),
                ),
                ("components", models.JSONField(blank=True, default=list)),
                ("meta_template_id", models.CharField(blank=True, max_length=64)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("name", "language")},
            },
        ),
        migrations.AddIndex(
            model_name="whatsappcontact",
            index=models.Index(
                fields=["user", "opt_in_status"], name="whatsapp_wh_user_id_f2fa6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappcartsession",
            index=models.Index(
                fields=["status", "expires_at"], name="whatsapp_wh_status_849a0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(
                fields=["conversation", "timestamp"],
                name="whatsapp_wh_convers_2934b2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(fields=["status"], name="whatsapp_wh_status_55e250_idx"),
        ),
    ]
