# Generated by Django 6.1.1 on 2026-10-04 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0007_add_order_channel_meta"),
        ("whatsapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsappcartsession",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="whatsapp_cart_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappcartsession",
            index=models.Index(
                fields=["user", "-created_at"], name="whatsapp_wh_user_id_4a27f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappcartsession",
            index=models.Index(
                fields=["contact", "-created_at"], name="whatsapp_wh_contact_d0a81f_idx"
            ),
        ),
    ]
