# Generated by Django 6.1.1 on 2026-10-02 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(db_index=True, max_length=64)),
                ("variant_id", models.CharField(blank=True, default="", max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(blank=True, max_length=120)),
                ("image", models.CharField(blank=True, max_length=500)),
                ("variant_label", models.CharField(blank=True, max_length=120)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "compare_at_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "stock",
                    models.CharField(
                        choices=[
                            ("In Stock", "In Stock"),
                            ("Low Stock", "Low Stock"),
                            ("Out of Stock", "Out of Stock"),
                        ],
                        default="In Stock",
                        max_length=20,
                    ),
                ),
                ("stock_count", models.PositiveIntegerField(default=0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="checkout.cart",
                    ),
                ),
            ],
            options={
                "ordering": ["-added_at"],
                "indexes": [
                    models.Index(
                        fields=["cart", "-added_at"],
                        name="checkout_ca_cart_id_008699_idx",
                    ),
                    models.Index(
                        fields=["cart", "product_id"],
                        name="checkout_ca_cart_id_e3f0d3_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cart", "product_id", "variant_id"),
                        name="one_cart_item_per_variant_per_cart",
                    )
                ],
            },
        ),
    ]
