# Generated by Django 6.1.1 on 2026-10-02 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "checkout",
            "0003_orderstatusevent_order_courier_order_internal_notes_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="contact_phone",
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                condition=models.Q(("user__isnull", True)),
                fields=["contact_email"],
                name="order_guest_email_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                condition=models.Q(("user__isnull", True)),
                fields=["contact_phone"],
                name="order_guest_phone_idx",
            ),
        ),
    ]
