# Generated by Django 6.1.1 on 2026-10-03 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0004_alter_order_contact_phone_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("active", "Active"),
                            ("failed", "Failed"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("detail", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReconciliationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("matched", "Matched"),
                            ("unmatched", "Unmatched"),
                            ("cash_paid", "Marked paid by cash"),
                            ("on_account", "Posted to account"),
                        ],
                        max_length=20,
                    ),
                ),
                ("actor_label", models.CharField(blank=True, max_length=120)),
                (
                    "matched_order_reference",
                    models.CharField(blank=True, max_length=64),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="collected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collected_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[("MPESA", "M-Pesa"), ("COD", "Cash on Delivery")],
                db_index=True,
                default="MPESA",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="raw_callback",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="payment",
            name="reversal_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reversals",
                to="checkout.payment",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="reversal_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="settled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                    ("TIMEOUT", "Timeout"),
                    ("REVERSED", "Reversed"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["method", "status", "-created_at"],
                name="checkout_pa_method_428157_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["method", "-created_at"], name="checkout_pa_method_3a9d59_idx"
            ),
        ),
        migrations.AddField(
            model_name="paymentevent",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="checkout.payment",
            ),
        ),
        migrations.AddField(
            model_name="reconciliationlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reconciliations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reconciliationlog",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reconciliations",
                to="checkout.payment",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentevent",
            index=models.Index(
                fields=["payment", "created_at"], name="checkout_pa_payment_4db189_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reconciliationlog",
            index=models.Index(
                fields=["payment", "-created_at"], name="checkout_re_payment_0c3c81_idx"
            ),
        ),
    ]
