# Generated by Django 6.1.1 on 2026-10-04 00:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "checkout",
            "0005_paymentevent_reconciliationlog_payment_collected_by_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="source",
            field=models.CharField(
                choices=[
                    ("web", "Web"),
                    ("whatsapp", "WhatsApp"),
                    ("admin", "Admin"),
                    ("phone", "Phone"),
                ],
                db_index=True,
                default="web",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["source", "-created_at"], name="checkout_or_source_eb0368_idx"
            ),
        ),
    ]
