# Generated by Django 6.1.1 on 2026-10-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0006_order_source_order_checkout_or_source_eb0368_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="channel_meta",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
