# Generated by Django 6.1.1 on 2026-10-03 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(db_index=True, max_length=64)),
                (
                    "quantity_delta",
                    models.IntegerField(
                        help_text="Signed. +10 for a restock, -3 for a sale."
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("sale", "Sale"),
                            ("restock", "Restock"),
                            ("adjustment", "Adjustment"),
                            ("damage", "Damage"),
                            ("return", "Return"),
                            ("correction", "Correction"),
                            ("transfer_in", "Transfer In"),
                            ("transfer_out", "Transfer Out"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Order reference, PO number, or manual adjustment ID.",
                        max_length=64,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock movement",
                "verbose_name_plural": "Stock movements",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product_id", "-created_at"],
                        name="dashboard_i_product_f8a879_idx",
                    ),
                    models.Index(
                        fields=["reason", "-created_at"],
                        name="dashboard_i_reason_760e76_idx",
                    ),
                ],
            },
        ),
    ]
