# Generated by Django 6.1.1 on 2026-10-04 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0004_alter_discount_promotion_type"),
        ("checkout", "0007_add_order_channel_meta"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("VIDEO", "Video"),
                            ("PHOTO_CAROUSEL", "Photo carousel"),
                            ("LIVE_PROMO", "LIVE promotion"),
                        ],
                        default="VIDEO",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IDEA", "Idea"),
                            ("SCRIPTED", "Scripted"),
                            ("FILMED", "Filmed"),
                            ("POSTED", "Posted"),
                        ],
                        default="IDEA",
                        max_length=16,
                    ),
                ),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                ("script", models.TextField(blank=True)),
                ("hashtags", models.CharField(blank=True, max_length=255)),
                ("posted_url", models.URLField(blank=True, max_length=500)),
                ("thumbnail_url", models.URLField(blank=True, max_length=500)),
                ("products", models.JSONField(blank=True, default=list)),
                ("views", models.PositiveIntegerField(default=0)),
                ("likes", models.PositiveIntegerField(default=0)),
                ("comments", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-scheduled_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LiveSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("scheduled_start", models.DateTimeField()),
                ("duration_min", models.PositiveIntegerField(default=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("LIVE", "Live"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=16,
                    ),
                ),
                ("products", models.JSONField(blank=True, default=list)),
                ("peak_viewers", models.PositiveIntegerField(default=0)),
                ("orders_generated", models.PositiveIntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("top_product", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-scheduled_start"],
            },
        ),
        migrations.CreateModel(
            name="Creator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "handle",
                    models.CharField(
                        help_text="TikTok handle without @, e.g. 'njeritech'",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("followers", models.PositiveIntegerField(default=0)),
                ("niche", models.CharField(blank=True, max_length=64)),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage, e.g. 15.00 for 15%",
                        max_digits=5,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("ENDED", "Ended"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DirectProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("SOLD_OUT", "Sold Out"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("viral", models.BooleanField(default=False)),
                ("video_link", models.URLField(blank=True, max_length=500)),
                ("low_stock_threshold", models.PositiveIntegerField(default=5)),
                ("linked_to_website", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direct_listing",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Direct Product",
                "verbose_name_plural": "Direct Products",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CreatorSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attributed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "commission_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("paid", models.BooleanField(default=False)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("payout_reference", models.CharField(blank=True, max_length=64)),
                ("notes", models.TextField(blank=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="direct_orders.creator",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creator_sales",
                        to="checkout.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-attributed_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("creator", "order"),
                        name="one_sale_per_creator_per_order",
                    )
                ],
            },
        ),
    ]
