# Generated by Django 6.1.1 on 2026-10-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("direct_orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentpost",
            options={"ordering": ["-scheduled_at", "-created_at"]},
        ),
        migrations.RemoveField(
            model_name="contentpost",
            name="scheduled_date",
        ),
        migrations.AddField(
            model_name="contentpost",
            name="caption",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="contentpost",
            name="platform",
            field=models.CharField(
                choices=[
                    ("TikTok", "TikTok"),
                    ("Instagram", "Instagram"),
                    ("YouTube", "YouTube"),
                    ("Facebook", "Facebook"),
                ],
                default="TikTok",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="contentpost",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentpost",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Public URL of the uploaded video. Empty for photo-only posts.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="creator",
            name="avatar_url",
            field=models.URLField(
                blank=True,
                help_text="Public URL of the creator's profile picture.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="creator",
            name="platform",
            field=models.CharField(
                choices=[
                    ("TikTok", "TikTok"),
                    ("Instagram", "Instagram"),
                    ("YouTube", "YouTube"),
                    ("Facebook", "Facebook"),
                ],
                default="TikTok",
                help_text="Primary platform this creator works on.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="livesession",
            name="host_name",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
