# Generated by Django 6.1.1 on 2026-10-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OverviewCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("range_key", models.CharField(max_length=64, unique=True)),
                ("payload", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Overview cache",
                "verbose_name_plural": "Overview cache",
                "indexes": [
                    models.Index(
                        fields=["range_key"], name="overview_ov_range_k_bb6b04_idx"
                    )
                ],
            },
        ),
    ]
