# Generated by Django 6.1.1 on 2026-10-03 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "checkout",
            "0005_paymentevent_reconciliationlog_payment_collected_by_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CourierConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "logo_bg",
                    models.CharField(
                        blank=True,
                        help_text="Tailwind colour class for the logo chip (e.g. 'bg-amber-500').",
                        max_length=64,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("api_key", models.CharField(blank=True, max_length=255)),
                ("enabled", models.BooleanField(db_index=True, default=False)),
                (
                    "regions",
                    models.JSONField(
                        default=list, help_text="Regions this courier serves."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Courier integration",
                "verbose_name_plural": "Courier integrations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PickupLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Locker", "Locker"),
                            ("Agent", "Agent"),
                            ("Store", "Store"),
                        ],
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("county", models.CharField(db_index=True, max_length=64)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("hours", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Disabled", "Disabled")],
                        db_index=True,
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pickup location",
                "verbose_name_plural": "Pickup locations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "default_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("eta", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Disabled", "Disabled")],
                        db_index=True,
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Shipping method",
                "verbose_name_plural": "Shipping methods",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ShippingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("region", models.CharField(max_length=64)),
                (
                    "counties",
                    models.JSONField(
                        default=list,
                        help_text="List of county names covered by this zone.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Shipping zone",
                "verbose_name_plural": "Shipping zones",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_number", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Label Created", "Label Created"),
                            ("Picked Up", "Picked Up"),
                            ("In Transit", "In Transit"),
                            ("Out for Delivery", "Out for Delivery"),
                            ("Delivered", "Delivered"),
                            ("Failed", "Failed"),
                            ("Returned", "Returned"),
                        ],
                        db_index=True,
                        default="Pending",
                        max_length=32,
                    ),
                ),
                ("destination", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment",
                        to="checkout.order",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipments",
                        to="shipping.courierconfig",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipments",
                        to="shipping.shippingmethod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipment",
                "verbose_name_plural": "Shipments",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-updated_at"],
                        name="shipping_sh_status_c03296_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ShippingRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("eta", models.CharField(blank=True, max_length=64)),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rates",
                        to="shipping.shippingmethod",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="shipping.shippingzone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping rate",
                "verbose_name_plural": "Shipping rates",
                "ordering": ["method__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("zone", "method"), name="one_rate_per_method_per_zone"
                    )
                ],
            },
        ),
    ]
