# Generated by Django 6.1.1 on 2026-10-01 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("checkout", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(default="Home", max_length=32)),
                ("full_name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=32)),
                ("street", models.CharField(max_length=255)),
                ("town", models.CharField(max_length=120)),
                ("county", models.CharField(max_length=120)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "-updated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("user",),
                        name="one_default_address_per_user",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("order", "Order"),
                            ("shipping", "Shipping"),
                            ("promo", "Promo"),
                            ("security", "Security"),
                            ("system", "System"),
                            ("review", "Review"),
                        ],
                        default="system",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                ("href", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="account_not_user_id_42f819_idx",
                    ),
                    models.Index(
                        fields=["user", "is_read"],
                        name="account_not_user_id_87f092_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(db_index=True, max_length=64)),
                ("product_name", models.CharField(max_length=255)),
                ("product_slug", models.CharField(blank=True, max_length=255)),
                ("product_image", models.CharField(blank=True, max_length=500)),
                ("product_brand", models.CharField(blank=True, max_length=120)),
                ("variant_label", models.CharField(blank=True, max_length=120)),
                ("rating", models.PositiveSmallIntegerField()),
                ("title", models.CharField(blank=True, max_length=200)),
                ("body", models.TextField()),
                ("images", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("rejection_reason", models.CharField(blank=True, max_length=255)),
                ("is_verified_purchase", models.BooleanField(default=False)),
                ("moderated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="checkout.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="account_rev_user_id_a392f8_idx",
                    ),
                    models.Index(
                        fields=["user", "product_id", "status"],
                        name="account_rev_user_id_ac1316_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "product_id"),
                        name="one_review_per_product_per_user",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WishlistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=64)),
                ("variant_id", models.CharField(max_length=64)),
                ("product_name", models.CharField(max_length=255)),
                ("product_slug", models.CharField(blank=True, max_length=255)),
                ("product_brand", models.CharField(blank=True, max_length=120)),
                ("product_image", models.CharField(blank=True, max_length=500)),
                ("variant_name", models.CharField(blank=True, max_length=120)),
                ("variant_image", models.CharField(blank=True, max_length=500)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "compare_at_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "stock",
                    models.CharField(
                        choices=[
                            ("In Stock", "In Stock"),
                            ("Low Stock", "Low Stock"),
                            ("Out of Stock", "Out of Stock"),
                        ],
                        default="In Stock",
                        max_length=20,
                    ),
                ),
                ("stock_count", models.PositiveIntegerField(default=0)),
                ("discount_percent", models.PositiveIntegerField(default=0)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-added_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-added_at"],
                        name="account_wis_user_id_f3b12b_idx",
                    ),
                    models.Index(
                        fields=["user", "variant_id"],
                        name="account_wis_user_id_8fa917_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "variant_id"),
                        name="one_wishlist_item_per_variant_per_user",
                    )
                ],
            },
        ),
    ]
