# Generated by Django 6.1.1 on 2026-10-03 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_review_moderated_by_wishlistitem_updated_at_and_more"),
        ("checkout", "0004_alter_order_contact_phone_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="review",
            name="flag_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="review",
            name="flag_status",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("flagged", "Flagged"),
                    ("resolved", "Resolved"),
                ],
                db_index=True,
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="flagged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="flagged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flagged_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="guest_author_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="review",
            name="helpful_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["flag_status", "-created_at"],
                name="account_rev_flag_st_dcbd8b_idx",
            ),
        ),
        migrations.AddField(
            model_name="reviewreply",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="review_replies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reviewreply",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="account.review",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewreply",
            index=models.Index(
                fields=["review", "created_at"], name="account_rev_review__eb3530_idx"
            ),
        ),
    ]
