# Generated by Django 6.1.1 on 2026-10-04 20:07

import dashboard.aiandautomations.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AISettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("groq", "Groq"),
                            ("openai", "OpenAI"),
                            ("gemini", "Google Gemini"),
                            ("openrouter", "OpenRouter"),
                            ("custom", "Custom"),
                        ],
                        default="groq",
                        max_length=32,
                    ),
                ),
                (
                    "model",
                    models.CharField(default="llama-3.3-70b-versatile", max_length=64),
                ),
                ("base_url", models.CharField(blank=True, default="", max_length=255)),
                ("api_key_encrypted", models.TextField(blank=True, default="")),
                (
                    "monthly_budget_kes",
                    models.DecimalField(decimal_places=2, default=1000, max_digits=12),
                ),
                ("budget_alert", models.BooleanField(default=True)),
                ("masking", models.BooleanField(default=True)),
                ("audit_retention_days", models.PositiveIntegerField(default=30)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Settings",
                "verbose_name_plural": "AI Settings",
            },
        ),
        migrations.CreateModel(
            name="Automation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=dashboard.aiandautomations.models._id,
                        editable=False,
                        max_length=24,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("trigger_event", models.CharField(max_length=100)),
                (
                    "trigger_label",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("timing", models.CharField(default="Immediately", max_length=50)),
                (
                    "action_type",
                    models.CharField(default="Send WhatsApp", max_length=50),
                ),
                ("template", models.CharField(blank=True, default="", max_length=100)),
                (
                    "variable_map",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("recipients", models.CharField(default="Customer", max_length=50)),
                ("admin_channel", models.CharField(default="Email", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Paused", "Paused"),
                            ("Draft", "Draft"),
                        ],
                        default="Draft",
                        max_length=12,
                    ),
                ),
                ("runs", models.PositiveIntegerField(default=0)),
                ("successes", models.PositiveIntegerField(default=0)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AutomationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("trigger", models.CharField(max_length=200)),
                ("trigger_event", models.CharField(max_length=100)),
                ("action", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="BulkJob",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=dashboard.aiandautomations.models._id,
                        editable=False,
                        max_length=24,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_ids", models.JSONField(default=list)),
                ("content_type", models.CharField(max_length=64)),
                ("tone", models.CharField(blank=True, default="", max_length=32)),
                ("language", models.CharField(blank=True, default="", max_length=32)),
                ("length", models.CharField(blank=True, default="", max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=12,
                    ),
                ),
                ("results", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContentDraft",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=dashboard.aiandautomations.models._id,
                        editable=False,
                        max_length=24,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_id", models.CharField(max_length=64)),
                ("content_type", models.CharField(max_length=64)),
                ("tone", models.CharField(blank=True, default="", max_length=32)),
                ("language", models.CharField(blank=True, default="", max_length=32)),
                ("length", models.CharField(blank=True, default="", max_length=32)),
                ("body", models.TextField()),
                ("published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Insight",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=dashboard.aiandautomations.models._id,
                        editable=False,
                        max_length=24,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sales", "Sales"),
                            ("inventory", "Inventory"),
                            ("customer", "Customer"),
                            ("channel", "Channel"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=10,
                    ),
                ),
                ("text", models.TextField()),
                ("action_label", models.CharField(max_length=100)),
                ("action_link", models.CharField(max_length=255)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("natural_language", models.BooleanField(default=True)),
                ("personalized", models.BooleanField(default=True)),
                ("explain", models.BooleanField(default=False)),
                ("cross_sell", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=dashboard.aiandautomations.models._id,
                        editable=False,
                        max_length=24,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("resource", models.CharField(blank=True, default="", max_length=100)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AutomationRun",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=dashboard.aiandautomations.models._id,
                        editable=False,
                        max_length=24,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_name", models.CharField(max_length=100)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("success", models.BooleanField(default=True)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "automation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="run_logs",
                        to="aiandautomations.automation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=dashboard.aiandautomations.models._id,
                        editable=False,
                        max_length=24,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="New chat", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=dashboard.aiandautomations.models._id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=12,
                    ),
                ),
                ("content", models.TextField()),
                ("chart_json", models.JSONField(blank=True, null=True)),
                ("table_json", models.JSONField(blank=True, null=True)),
                ("link_json", models.JSONField(blank=True, null=True)),
                ("tokens_in", models.PositiveIntegerField(default=0)),
                ("tokens_out", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="aiandautomations.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=dashboard.aiandautomations.models._id,
                        editable=False,
                        max_length=24,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query", models.CharField(max_length=255)),
                ("results_count", models.PositiveIntegerField(default=0)),
                ("converted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["query"], name="aiandautoma_query_c456ef_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="UsageEvent",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=dashboard.aiandautomations.models._id,
                        editable=False,
                        max_length=24,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("assistant", "Assistant"),
                            ("content", "Content Gen"),
                            ("search", "Search"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tokens_in", models.PositiveIntegerField(default=0)),
                ("tokens_out", models.PositiveIntegerField(default=0)),
                (
                    "cost_kes",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                ("day", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["day", "feature"], name="aiandautoma_day_925d4a_idx"
                    )
                ],
            },
        ),
    ]
