# Generated by Django 5.2.17 on 2026-09-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialaccount",
            name="shop_cipher",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="socialaccount",
            name="platform",
            field=models.CharField(
                choices=[
                    ("YOUTUBE", "YouTube"),
                    ("FACEBOOK", "Facebook"),
                    ("INSTAGRAM", "Instagram"),
                    ("X", "X (Twitter)"),
                    ("TIKTOK_SHOP", "TikTok Shop"),
                ],
                max_length=20,
            ),
        ),
    ]
