# Generated by Django 6.1.1 on 2026-10-05 17:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "authentication",
            "0002_passwordresettoken_userinvite_user_invited_by_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                ("description", models.TextField()),
                ("scope", models.CharField(max_length=64)),
                ("color", models.CharField(max_length=64)),
                ("icon", models.CharField(max_length=32)),
                ("is_customer", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "dashboard_roles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ModulePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module", models.CharField(max_length=64)),
                ("group", models.CharField(max_length=32)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Administrator", "Administrator"),
                            ("Manager", "Manager"),
                            ("Sales Staff", "Sales Staff"),
                            ("Inventory Staff", "Inventory Staff"),
                            ("Marketing Staff", "Marketing Staff"),
                            ("Support Staff", "Support Staff"),
                        ],
                        max_length=32,
                    ),
                ),
                ("granted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "dashboard_module_permissions",
                "ordering": ["group", "module", "role"],
                "unique_together": {("module", "role")},
            },
        ),
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="staff_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Administrator", "Administrator"),
                            ("Manager", "Manager"),
                            ("Sales Staff", "Sales Staff"),
                            ("Inventory Staff", "Inventory Staff"),
                            ("Marketing Staff", "Marketing Staff"),
                            ("Support Staff", "Support Staff"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Invited", "Invited"),
                            ("Suspended", "Suspended"),
                        ],
                        default="Invited",
                        max_length=16,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=64)),
                ("avatar", models.URLField(blank=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "dashboard_staff_profiles",
                "indexes": [
                    models.Index(fields=["role"], name="dashboard_s_role_b88a22_idx"),
                    models.Index(
                        fields=["status"], name="dashboard_s_status_e271a2_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StaffInvite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=150)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Administrator", "Administrator"),
                            ("Manager", "Manager"),
                            ("Sales Staff", "Sales Staff"),
                            ("Inventory Staff", "Inventory Staff"),
                            ("Marketing Staff", "Marketing Staff"),
                            ("Support Staff", "Support Staff"),
                        ],
                        max_length=32,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=64)),
                ("message", models.TextField(blank=True)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_staff_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_staff_invites",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="dashboard_s_email_5c471d_idx"),
                    models.Index(fields=["token"], name="dashboard_s_token_eb7a71_idx"),
                ],
            },
        ),
    ]
