# Generated by Django 6.1.1 on 2026-10-06 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_users", "0002_seed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={"ordering": ["is_customer", "name"]},
        ),
        migrations.RemoveField(
            model_name="staffprofile",
            name="last_login_at",
        ),
        migrations.AddField(
            model_name="staffinvite",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accepted_staff_invites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="staffinvite",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staffinvite",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                    ("Cancelled", "Cancelled"),
                    ("Expired", "Expired"),
                ],
                default="Pending",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="modulepermission",
            name="role",
            field=models.CharField(
                choices=[
                    ("Administrator", "Administrator"),
                    ("Manager", "Manager"),
                    ("Sales Staff", "Sales Staff"),
                    ("Inventory Staff", "Inventory Staff"),
                    ("Marketing Staff", "Marketing Staff"),
                    ("Support Staff", "Support Staff"),
                    ("Customer", "Customer"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="modulepermission",
            index=models.Index(
                fields=["role", "granted"], name="dashboard_m_role_7c817f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffinvite",
            index=models.Index(fields=["status"], name="dashboard_s_status_eb0665_idx"),
        ),
    ]
