# Generated by Django 5.2.17 on 2026-09-27 10:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreWhatsAppConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=20)),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "template",
                    models.TextField(
                        blank=True,
                        default="Hello {store_name}, I'd like to order:\n{items}\nTotal: {total}\nMy delivery address: {address}",
                    ),
                ),
                ("new_order_alert", models.BooleanField(default=True)),
                ("auto_reply", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Store WhatsApp config",
                "db_table": "store_whatsapp_configs",
            },
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(
                fields=["direction", "status"], name="whatsapp_me_directi_bdbee3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(
                fields=["from_number", "created_at"],
                name="whatsapp_me_from_nu_b9a633_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(
                fields=["to_number", "created_at"],
                name="whatsapp_me_to_numb_075956_idx",
            ),
        ),
        migrations.AddField(
            model_name="storewhatsappconfig",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="whatsapp_config",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
