# Generated by Django 5.2.17 on 2026-09-27 10:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingZone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("counties", models.JSONField(blank=True, default=list)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "shipping_zones",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="BusinessDetails",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("sole", "Sole Proprietor"),
                            ("ltd", "Limited Company"),
                            ("partner", "Partnership"),
                            ("none", "Not registered"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("kra_pin", models.CharField(blank=True, max_length=20)),
                ("reg_number", models.CharField(blank=True, max_length=40)),
                ("vat_registered", models.BooleanField(default=False)),
                ("vat_number", models.CharField(blank=True, max_length=30)),
                ("etims_enabled", models.BooleanField(default=False)),
                ("etims_device_id", models.CharField(blank=True, max_length=80)),
                ("etims_pin", models.CharField(blank=True, max_length=80)),
                ("etims_api_key", models.CharField(blank=True, max_length=255)),
                (
                    "etims_env",
                    models.CharField(
                        choices=[("sandbox", "Sandbox"), ("production", "Production")],
                        default="sandbox",
                        max_length=20,
                    ),
                ),
                (
                    "invoice_footer",
                    models.CharField(
                        default="Thank you for shopping with us!", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Business details",
                "db_table": "business_details",
            },
        ),
        migrations.CreateModel(
            name="ShippingRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("method", models.CharField(default="Standard", max_length=80)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("eta", models.CharField(blank=True, max_length=80)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="admin_dashboard.shippingzone",
                    ),
                ),
            ],
            options={
                "db_table": "shipping_rates",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoreProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("tagline", models.CharField(blank=True, max_length=160)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="stores/logos/"),
                ),
                ("street", models.CharField(blank=True, max_length=160)),
                ("town", models.CharField(blank=True, max_length=80)),
                ("county", models.CharField(blank=True, max_length=40)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(default="Kenya", max_length=60)),
                ("support_email", models.EmailField(blank=True, max_length=254)),
                ("support_phone", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "store_profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoreShippingConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "preset",
                    models.CharField(
                        choices=[
                            ("national", "Nationwide (Kenya)"),
                            ("nairobi", "Nairobi only"),
                            ("custom", "Custom"),
                        ],
                        default="national",
                        max_length=20,
                    ),
                ),
                ("free_shipping_enabled", models.BooleanField(default=False)),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "store_shipping_configs",
            },
        ),
        migrations.AddField(
            model_name="shippingzone",
            name="config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zones",
                to="admin_dashboard.storeshippingconfig",
            ),
        ),
        migrations.CreateModel(
            name="StoreTheme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "preset",
                    models.CharField(
                        choices=[
                            ("blue", "Trust Blue"),
                            ("dark", "Tech Dark"),
                            ("white", "Clean White"),
                            ("orange", "Warm Orange"),
                            ("green", "Fresh Green"),
                            ("red", "Bold Red"),
                            ("custom", "Custom"),
                        ],
                        default="blue",
                        max_length=20,
                    ),
                ),
                ("primary", models.CharField(default="#1e3a8a", max_length=7)),
                ("accent", models.CharField(default="#3b82f6", max_length=7)),
                (
                    "font",
                    models.CharField(
                        choices=[
                            ("Inter", "Inter"),
                            ("Poppins", "Poppins"),
                            ("Roboto", "Roboto"),
                        ],
                        default="Inter",
                        max_length=20,
                    ),
                ),
                ("radius", models.PositiveSmallIntegerField(default=4)),
                ("dark_store", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Store theme",
                "db_table": "store_themes",
            },
        ),
    ]
