# Generated by Django 6.1.1 on 2026-10-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyticsCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tab",
                    models.CharField(
                        choices=[
                            ("traffic", "Traffic"),
                            ("sales", "Sales"),
                            ("customers", "Customers"),
                            ("products", "Products"),
                            ("channels", "Channels"),
                        ],
                        max_length=32,
                    ),
                ),
                ("range_key", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Analytics cache",
                "verbose_name_plural": "Analytics cache",
                "indexes": [
                    models.Index(
                        fields=["tab", "range_key"], name="analytics_a_tab_bdf708_idx"
                    )
                ],
                "unique_together": {("tab", "range_key")},
            },
        ),
    ]
