# Generated by Django 6.1.1 on 2026-10-05 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "Mobile"),
                            ("desktop", "Desktop"),
                            ("tablet", "Tablet"),
                            ("bot", "Bot"),
                        ],
                        max_length=16,
                    ),
                ),
                ("user_agent", models.TextField(blank=True)),
                ("session_key", models.CharField(blank=True, max_length=64)),
                ("referrer", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="page_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Page view",
                "verbose_name_plural": "Page views",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at", "device_type"],
                        name="analytics_p_created_a07a9d_idx",
                    ),
                    models.Index(fields=["path"], name="analytics_p_path_3382b5_idx"),
                ],
            },
        ),
    ]
