# Generated by Django 5.2.17 on 2026-09-28 09:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not started"),
                            ("IN_PROGRESS", "In progress"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        choices=[
                            ("step1", "step1"),
                            ("step2", "step2"),
                            ("step3", "step3"),
                            ("step4", "step4"),
                            ("step5", "step5"),
                            ("step6", "step6"),
                            ("step7", "step7"),
                            ("step8", "step8"),
                            ("step9", "step9"),
                            ("step10", "step10"),
                            ("step11", "step11"),
                            ("step12", "step12"),
                        ],
                        default="step1",
                        max_length=16,
                    ),
                ),
                ("completion_percent", models.PositiveSmallIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_session",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "onboarding_onboardingsession",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingStepData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("step1", "step1"),
                            ("step2", "step2"),
                            ("step3", "step3"),
                            ("step4", "step4"),
                            ("step5", "step5"),
                            ("step6", "step6"),
                            ("step7", "step7"),
                            ("step8", "step8"),
                            ("step9", "step9"),
                            ("step10", "step10"),
                            ("step11", "step11"),
                            ("step12", "step12"),
                        ],
                        max_length=16,
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("is_complete", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_data",
                        to="onboarding.onboardingsession",
                    ),
                ),
            ],
            options={
                "db_table": "onboarding_onboardingstepdata",
                "ordering": ["session", "step"],
                "indexes": [
                    models.Index(
                        fields=["session", "step"],
                        name="onboarding__session_8c7af0_idx",
                    )
                ],
                "unique_together": {("session", "step")},
            },
        ),
    ]
