"""
account/views/addresses.py

Saved delivery addresses. All endpoints require authentication and
scope by `user=request.user`.

Endpoints:

    GET    /api/v1/account/addresses/                        — list
    POST   /api/v1/account/addresses/                        — create
    GET    /api/v1/account/addresses/<pk>/                   — fetch one
    PATCH  /api/v1/account/addresses/<pk>/                   — update
    DELETE /api/v1/account/addresses/<pk>/                   — delete
    POST   /api/v1/account/addresses/<pk>/set-default/       — promote

THE DEFAULT ADDRESS INVARIANT
-----------------------------
At any point after the customer's first create, exactly one address
is marked default. Two mechanisms enforce this:

  1. A partial unique index on `(user)` where `is_default=True` — the
     `one_default_address_per_user` constraint on the model. This is
     generated by Django's `UniqueConstraint(..., condition=Q(...))`
     as a real partial index on Postgres; no raw SQL needed.

  2. Row-lock serialization on every write that touches `is_default`.
     Each mutating view does `User.objects.select_for_update()` at
     the top of its transaction, so two concurrent POSTs / PATCHes /
     DELETEs for the same user cannot interleave their "check then
     write" logic. Without the lock, the unique constraint catches
     the worst case as a 500 — with the lock, it never fires.

WHY THE FIRST ADDRESS IS FORCED DEFAULT
---------------------------------------
A customer with one address and no default would force the checkout
page to pick arbitrarily. Making "first = default" the rule means the
invariant above holds at every point after the first create. The
serializer doesn't decide this — the view does, based on whether any
address already exists for the user.
"""

from django.contrib.auth import get_user_model
from django.db import transaction
from django.shortcuts import get_object_or_404

from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from ..models import Address
from ..serializers import AddressInputSerializer, AddressSerializer

User = get_user_model()


# ─────────────────────────────────────────────────────────────────────────────
# Internal helper
# ─────────────────────────────────────────────────────────────────────────────
def _lock_user(user):
    """
    Acquire a row lock on the caller's User row.

    Must be called inside a `transaction.atomic()` block. Serializes
    every address write for the same user — the second writer's
    "does anything already exist?" check runs after the first
    writer's transaction commits, so the check sees the truth.

    Does not modify the user; only the lock matters. The returned
    instance is discarded by callers.
    """
    User.objects.select_for_update().get(pk=user.pk)


# ─────────────────────────────────────────────────────────────────────────────
# List / create
# ─────────────────────────────────────────────────────────────────────────────
class AddressListCreateView(APIView):
    """
    GET  /api/v1/account/addresses/
    POST /api/v1/account/addresses/

    Response shape matches `lib/api.ts` Address:

        {
          id, label, full_name, phone, street, town, county,
          postal_code, is_default, created_at, updated_at
        }

    The list is ordered by the model's Meta (`-is_default`, `-updated_at`),
    so the default address always appears first — matches how the
    frontend renders the grid.
    """

    permission_classes = [IsAuthenticated]

    def get(self, request):
        qs = Address.objects.filter(user=request.user)
        return Response(AddressSerializer(qs, many=True).data)

    @transaction.atomic
    def post(self, request):
        # Serialize concurrent creates for this user. Two parallel
        # first-address POSTs would otherwise both see "no addresses"
        # and both try to create a default, tripping the partial
        # unique index with an IntegrityError → 500.
        _lock_user(request.user)

        ser = AddressInputSerializer(data=request.data)
        ser.is_valid(raise_exception=True)

        # First address is always default, regardless of what the
        # client sent. Subsequent addresses honour the `is_default`
        # flag as long as it's true — there's no path here that ends
        # with zero defaults when at least one address exists.
        is_first = not Address.objects.filter(user=request.user).exists()
        make_default = is_first or bool(
            ser.validated_data.get("is_default", False)
        )

        # Clear any previous default before creating the new one —
        # same transaction, so a crash between the two writes can't
        # leave two defaults or zero.
        if make_default:
            Address.objects.filter(user=request.user).update(
                is_default=False
            )

        address = Address.objects.create(
            user=request.user,
            **{**ser.validated_data, "is_default": make_default},
        )
        return Response(
            AddressSerializer(address).data,
            status=status.HTTP_201_CREATED,
        )


# ─────────────────────────────────────────────────────────────────────────────
# Detail — fetch / update / delete
# ─────────────────────────────────────────────────────────────────────────────
class AddressDetailView(APIView):
    """
    GET    /api/v1/account/addresses/<pk>/
    PATCH  /api/v1/account/addresses/<pk>/
    DELETE /api/v1/account/addresses/<pk>/

    Ownership-scoped: `get_object_or_404` filters by `user=request.user`,
    so a customer can only touch their own addresses. A foreign id
    returns 404, not 403 — the response shape is identical whether the
    address belongs to someone else or doesn't exist.
    """

    permission_classes = [IsAuthenticated]

    def get(self, request, pk):
        address = get_object_or_404(
            Address, pk=pk, user=request.user
        )
        return Response(AddressSerializer(address).data)

    @transaction.atomic
    def patch(self, request, pk):
        _lock_user(request.user)

        address = get_object_or_404(
            Address, pk=pk, user=request.user
        )
        ser = AddressInputSerializer(
            address, data=request.data, partial=True
        )
        ser.is_valid(raise_exception=True)

        requested_default = ser.validated_data.get("is_default")

        if requested_default is True:
            # Promotion: clear every other default for this user.
            Address.objects.filter(user=request.user).exclude(
                pk=pk
            ).update(is_default=False)

        elif requested_default is False and address.is_default:
            # Un-promotion is refused. Silently keep the flag on so
            # the customer always has exactly one default address
            # when they have at least one address. The correct path
            # to change the default is to promote a *different*
            # address — via set-default or by toggling that address's
            # checkbox.
            ser.validated_data["is_default"] = True

        ser.save()
        return Response(AddressSerializer(address).data)

    @transaction.atomic
    def delete(self, request, pk):
        """
        Delete an address. If it was the default, promote another one
        in the same transaction so the customer is never left with a
        set of addresses where none is marked default.

        Replacement choice: the most recently updated remaining
        address. Rationale is heuristic — the address the customer
        touched last is likely the one they're still using. Explicit
        ordering (`-updated_at`) is used instead of relying on the
        model's Meta, which also sorts by `-is_default` (irrelevant
        after the target row is gone).
        """
        _lock_user(request.user)

        address = get_object_or_404(
            Address, pk=pk, user=request.user
        )
        was_default = address.is_default
        address.delete()

        if was_default:
            replacement = (
                Address.objects.filter(user=request.user)
                .order_by("-updated_at")
                .first()
            )
            if replacement and not replacement.is_default:
                replacement.is_default = True
                replacement.save(update_fields=["is_default"])

        return Response(status=status.HTTP_204_NO_CONTENT)


# ─────────────────────────────────────────────────────────────────────────────
# Set default
# ─────────────────────────────────────────────────────────────────────────────
class AddressSetDefaultView(APIView):
    """
    POST /api/v1/account/addresses/<pk>/set-default/

    Promotes one address to default and clears every other. Wrapped in
    a transaction so a concurrent read never sees two defaults or zero.

    Returns the promoted address serialized, so the frontend can sync
    its local state from one response instead of refetching the list.
    """

    permission_classes = [IsAuthenticated]

    @transaction.atomic
    def post(self, request, pk):
        _lock_user(request.user)

        address = get_object_or_404(
            Address, pk=pk, user=request.user
        )

        # Unset every other default for this user, then set this one.
        # The `.exclude(pk=pk)` avoids a pointless write when the
        # target is already the default.
        Address.objects.filter(user=request.user).exclude(
            pk=pk
        ).update(is_default=False)

        if not address.is_default:
            address.is_default = True
            address.save(update_fields=["is_default"])

        return Response(AddressSerializer(address).data)