# Generated by Django 5.2.17 on 2026-09-27 10:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StorePaymentConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mpesa_enabled", models.BooleanField(default=False)),
                ("mpesa_consumer_key", models.CharField(blank=True, max_length=255)),
                ("mpesa_consumer_secret", models.CharField(blank=True, max_length=255)),
                ("mpesa_passkey", models.CharField(blank=True, max_length=255)),
                ("mpesa_shortcode", models.CharField(blank=True, max_length=20)),
                (
                    "mpesa_env",
                    models.CharField(
                        choices=[("sandbox", "Sandbox"), ("production", "Production")],
                        default="sandbox",
                        max_length=20,
                    ),
                ),
                (
                    "aggregator",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("pesapal", "Pesapal"),
                            ("dusupay", "Dusupay"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("aggregator_public_key", models.CharField(blank=True, max_length=255)),
                ("aggregator_secret_key", models.CharField(blank=True, max_length=255)),
                (
                    "aggregator_env",
                    models.CharField(
                        choices=[("sandbox", "Sandbox"), ("production", "Production")],
                        default="sandbox",
                        max_length=20,
                    ),
                ),
                ("mpesa_tested_at", models.DateTimeField(blank=True, null=True)),
                ("mpesa_test_ok", models.BooleanField(default=False)),
                ("aggregator_tested_at", models.DateTimeField(blank=True, null=True)),
                ("aggregator_test_ok", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Store payment config",
                "db_table": "store_payment_configs",
            },
        ),
    ]
