# Generated by Django 6.1.1 on 2026-10-05 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tab",
                    models.CharField(
                        choices=[
                            ("sales", "Sales"),
                            ("orders", "Orders"),
                            ("customers", "Customers"),
                            ("products", "Products"),
                            ("inventory", "Inventory"),
                            ("payments", "Payments"),
                            ("taxes", "Taxes & VAT"),
                            ("shipping", "Shipping"),
                            ("discounts", "Discounts"),
                            ("social", "Social Videos"),
                        ],
                        max_length=32,
                    ),
                ),
                ("range_key", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Report cache",
                "verbose_name_plural": "Report cache",
                "unique_together": {("tab", "range_key")},
            },
        ),
        migrations.CreateModel(
            name="ReportExportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tab", models.CharField(max_length=32)),
                ("range_key", models.CharField(max_length=64)),
                (
                    "fmt",
                    models.CharField(
                        choices=[("CSV", "CSV"), ("Excel", "Excel"), ("PDF", "PDF")],
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Report export log",
                "verbose_name_plural": "Report export logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
