# Generated by Django 6.1.1 on 2026-10-01 18:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("subject", models.CharField(max_length=200)),
                (
                    "body",
                    models.TextField(help_text="Plain text. Newlines become <p> tags."),
                ),
                ("hero_image_url", models.CharField(blank=True, max_length=500)),
                ("cta_text", models.CharField(blank=True, max_length=64)),
                ("cta_url", models.CharField(blank=True, max_length=500)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Welcome", "Welcome"),
                            ("Promotional", "Promotional"),
                            ("Transactional", "Transactional"),
                            ("Re-engagement", "Re-engagement"),
                        ],
                        db_index=True,
                        default="Promotional",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email Template",
                "verbose_name_plural": "Email Templates",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal label for the campaign; not visible to recipients.",
                        max_length=200,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("hero_image_url", models.CharField(blank=True, max_length=500)),
                ("body", models.TextField(help_text="Plain text with {{merge_tags}}.")),
                ("cta_text", models.CharField(blank=True, max_length=64)),
                ("cta_url", models.CharField(blank=True, max_length=500)),
                (
                    "audience_type",
                    models.CharField(
                        choices=[
                            ("all_active", "All Active Subscribers"),
                            ("list", "List"),
                            ("segment", "Segment"),
                        ],
                        default="all_active",
                        max_length=16,
                    ),
                ),
                (
                    "audience_id",
                    models.CharField(
                        blank=True,
                        help_text="List id or segment id; empty for 'all_active'.",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("queued", "Queued"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("paused", "Paused"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("recipient_count", models.PositiveIntegerField(default=0)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("open_count", models.PositiveIntegerField(default=0)),
                ("click_count", models.PositiveIntegerField(default=0)),
                ("bounce_count", models.PositiveIntegerField(default=0)),
                ("unsubscribe_count", models.PositiveIntegerField(default=0)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Audit: which template this campaign was seeded from.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns",
                        to="newsletter.emailtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Normalized to lowercase on save.",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional display name; may be edited in the admin.",
                        max_length=120,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Free-form labels, e.g. ['vip', 'buyer', 'student'].",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="False once the user unsubscribes.",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="homepage",
                        help_text="Where the signup came from (e.g. 'homepage', 'checkout').",
                        max_length=64,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Best-effort capture for abuse mitigation.",
                        null=True,
                    ),
                ),
                (
                    "unsubscribe_token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Used for one-click unsubscribe links in emails.",
                        unique=True,
                    ),
                ),
                (
                    "subscribed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Last time this address (re)subscribed.",
                    ),
                ),
                (
                    "unsubscribed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when is_active flips to False.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subscriber",
                "verbose_name_plural": "Subscribers",
                "ordering": ["-subscribed_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "-subscribed_at"],
                        name="newsletter__is_acti_0d811e_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CampaignRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Snapshot of the address at send time.",
                        max_length=254,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="newsletter.campaign",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null if the subscriber was deleted after the send.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaign_recipients",
                        to="newsletter.subscriber",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Recipient",
                "verbose_name_plural": "Campaign Recipients",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriberList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Tailwind class fragment for the badge, e.g. 'bg-blue-50 text-blue-950 border-blue-100'.",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscribers",
                    models.ManyToManyField(
                        blank=True, related_name="lists", to="newsletter.subscriber"
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscriber List",
                "verbose_name_plural": "Subscriber Lists",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["status", "-created_at"], name="newsletter__status_ee863f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaignrecipient",
            index=models.Index(
                fields=["campaign", "status"], name="newsletter__campaig_da95e7_idx"
            ),
        ),
    ]
