# Generated by Django 6.1.1 on 2026-10-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("HOME_HERO", "Homepage hero"),
                            ("CATEGORY_HERO", "Category hero"),
                            ("PROMO_STRIP", "Promo strip"),
                        ],
                        default="HOME_HERO",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                ("badge", models.CharField(blank=True, max_length=200)),
                ("headline", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                ("desktop_image", models.CharField(blank=True, max_length=500)),
                ("tablet_image", models.CharField(blank=True, max_length=500)),
                ("mobile_image", models.CharField(blank=True, max_length=500)),
                ("primary_cta_text", models.CharField(blank=True, max_length=80)),
                ("primary_cta_href", models.CharField(blank=True, max_length=300)),
                ("secondary_cta_text", models.CharField(blank=True, max_length=80)),
                ("secondary_cta_href", models.CharField(blank=True, max_length=300)),
                (
                    "text_alignment",
                    models.CharField(
                        choices=[
                            ("LEFT", "Left"),
                            ("CENTER", "Center"),
                            ("RIGHT", "Right"),
                        ],
                        default="LEFT",
                        max_length=10,
                    ),
                ),
                (
                    "overlay_style",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("DARK", "Dark"),
                            ("LIGHT", "Light"),
                            ("GRADIENT", "Gradient"),
                        ],
                        default="GRADIENT",
                        max_length=10,
                    ),
                ),
                ("overlay_opacity", models.PositiveSmallIntegerField(default=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SCHEDULED", "Scheduled"),
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("conversions", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "id"],
                "indexes": [
                    models.Index(
                        fields=["placement", "status", "order"],
                        name="banners_ban_placeme_e745ff_idx",
                    )
                ],
            },
        ),
    ]
