"""Seed banners — 1:1 with SEED_BANNERS in lib/bannerStore.ts.

Dates are ISO strings; the seed command parses them with parse_datetime().
"""

SEED_BANNERS = [
    {
        'id': 1,
        'name': 'Featured Collection',
        'placement': 'HOME_HERO',
        'order': 1,
        'badge': 'Featured Collection • New Season',
        'headline': 'Top Picks Across Every Category.',
        'description': (
            'Handpicked electronics from the brands customers trust most — '
            'smartphones, laptops, audio, and accessories, all in stock and '
            'ready to ship.'
        ),
        'desktop_image': '/hero01.png',
        'tablet_image': '',
        'mobile_image': '',
        'primary_cta_text': 'Shop Collection',
        'primary_cta_href': '/pages/products',
        'secondary_cta_text': 'Best Sellers',
        'secondary_cta_href': '/pages/products/bestsellingproducts',
        'text_alignment': 'LEFT',
        'overlay_style': 'GRADIENT',
        'overlay_opacity': 80,
        'status': 'ACTIVE',
        'start_at': None,
        'end_at': None,
        'impressions': 12480,
        'clicks': 892,
        'conversions': 74,
        'updated_at': '2026-09-25T14:20:00Z',
    },
    {
        'id': 2,
        'name': 'Visit Our Store — Westlands',
        'placement': 'HOME_HERO',
        'order': 2,
        'badge': 'Visit Our Store • Westlands Nairobi',
        'headline': 'Experience Tech In Person.',
        'description': (
            'Walk in, try before you buy, and get help from our team in '
            'minutes. Two locations open 7 days a week.'
        ),
        'desktop_image': '/hero02.png',
        'tablet_image': '',
        'mobile_image': '',
        'primary_cta_text': 'Find A Store',
        'primary_cta_href': '/stores',
        'secondary_cta_text': 'Talk To Us',
        'secondary_cta_href': '/support',
        'text_alignment': 'LEFT',
        'overlay_style': 'GRADIENT',
        'overlay_opacity': 80,
        'status': 'ACTIVE',
        'start_at': None,
        'end_at': None,
        'impressions': 20110,
        'clicks': 1432,
        'conversions': 96,
        'updated_at': '2026-09-28T10:05:00Z',
    },
    {
        'id': 3,
        'name': 'Smart Appliances',
        'placement': 'HOME_HERO',
        'order': 3,
        'badge': 'Modern Living • Smart Appliances',
        'headline': 'Smart Appliances For Modern Homes.',
        'description': (
            'Fridges, power stations, and connected devices engineered for '
            'reliability — even when the grid is not.'
        ),
        'desktop_image': '/hero03.png',
        'tablet_image': '',
        'mobile_image': '',
        'primary_cta_text': 'Shop Smart Home',
        'primary_cta_href': '/pages/products',
        'secondary_cta_text': 'View Power Stations',
        'secondary_cta_href': '/pages/products',
        'text_alignment': 'LEFT',
        'overlay_style': 'GRADIENT',
        'overlay_opacity': 80,
        'status': 'ACTIVE',
        'start_at': None,
        'end_at': None,
        'impressions': 9810,
        'clicks': 640,
        'conversions': 51,
        'updated_at': '2026-09-24T09:12:00Z',
    },
    {
        'id': 4,
        'name': 'Top Rated This Month',
        'placement': 'HOME_HERO',
        'order': 4,
        'badge': 'Customer Favorites • Top Rated',
        'headline': 'The Best Products This Month.',
        'description': (
            'Ranked by real customer reviews. Nothing under 4.6 stars makes '
            'this list.'
        ),
        'desktop_image': '/hero04.png',
        'tablet_image': '',
        'mobile_image': '',
        'primary_cta_text': 'Shop Best Sellers',
        'primary_cta_href': '/pages/products/bestsellingproducts',
        'secondary_cta_text': 'Read Reviews',
        'secondary_cta_href': '/pages/products',
        'text_alignment': 'LEFT',
        'overlay_style': 'GRADIENT',
        'overlay_opacity': 80,
        'status': 'ACTIVE',
        'start_at': None,
        'end_at': None,
        'impressions': 15220,
        'clicks': 1105,
        'conversions': 88,
        'updated_at': '2026-09-26T11:40:00Z',
    },
    {
        'id': 5,
        'name': 'New Arrivals',
        'placement': 'HOME_HERO',
        'order': 5,
        'badge': 'Just Landed • New Arrivals',
        'headline': 'New Products, Straight Off The Truck.',
        'description': (
            'The latest gear added this month — from M4 MacBooks to next-gen '
            'controllers. First come, first served.'
        ),
        'desktop_image': '/hero05.png',
        'tablet_image': '',
        'mobile_image': '',
        'primary_cta_text': 'Shop New Arrivals',
        'primary_cta_href': '/pages/products/newarrivals',
        'secondary_cta_text': 'Special Deals',
        'secondary_cta_href': '/pages/products/specialdeals',
        'text_alignment': 'LEFT',
        'overlay_style': 'GRADIENT',
        'overlay_opacity': 80,
        'status': 'ACTIVE',
        'start_at': None,
        'end_at': None,
        'impressions': 11020,
        'clicks': 830,
        'conversions': 63,
        'updated_at': '2026-09-27T16:00:00Z',
    },
    {
        'id': 6,
        'name': 'Browse By Category',
        'placement': 'HOME_HERO',
        'order': 6,
        'badge': 'Browse By Category',
        'headline': 'Find Exactly What You Need.',
        'description': (
            'Every product organized into clear categories — no endless '
            'scrolling, no guesswork.'
        ),
        'desktop_image': '/hero06.png',
        'tablet_image': '',
        'mobile_image': '',
        'primary_cta_text': 'View All Categories',
        'primary_cta_href': '/pages/categories',
        'secondary_cta_text': 'Shop All',
        'secondary_cta_href': '/pages/products',
        'text_alignment': 'LEFT',
        'overlay_style': 'GRADIENT',
        'overlay_opacity': 80,
        'status': 'ACTIVE',
        'start_at': None,
        'end_at': None,
        'impressions': 8760,
        'clicks': 512,
        'conversions': 39,
        'updated_at': '2026-09-23T08:30:00Z',
    },
]