# Generated by Django 6.1.1 on 2026-10-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WhatsAppConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Turn the floating button on or off across the storefront.",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="E.164 without +, e.g. 254712345678. Used to build wa.me links.",
                        max_length=20,
                    ),
                ),
                (
                    "display_number",
                    models.CharField(
                        blank=True,
                        help_text="Human-friendly number shown in the panel footer.",
                        max_length=32,
                    ),
                ),
                (
                    "shop_name",
                    models.CharField(
                        help_text='Shown in the panel header: "Chat with <shop name>".',
                        max_length=120,
                    ),
                ),
                (
                    "hours_label",
                    models.CharField(
                        blank=True,
                        help_text='Short status line, e.g. "Mon–Sat, 9am–6pm".',
                        max_length=120,
                    ),
                ),
                (
                    "default_message",
                    models.TextField(
                        blank=True,
                        help_text='Prefilled message when the customer taps "Open WhatsApp".',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "WhatsApp Float Config",
                "verbose_name_plural": "WhatsApp Float Config",
                "db_table": "whatsapp_whatsappconfig",
            },
        ),
        migrations.CreateModel(
            name="WhatsAppQuickAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                (
                    "message",
                    models.TextField(
                        help_text="Prefilled WhatsApp message sent when this button is tapped."
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("shopping_bag", "Shopping bag"),
                            ("package", "Package"),
                            ("truck", "Truck"),
                            ("headphones", "Headphones"),
                            ("message", "Message"),
                            ("clock", "Clock"),
                        ],
                        default="message",
                        max_length=24,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "WhatsApp Quick Action",
                "verbose_name_plural": "WhatsApp Quick Actions",
                "db_table": "whatsapp_whatsappquickaction",
                "ordering": ["order", "id"],
            },
        ),
    ]
