# Generated by Django 6.1.1 on 2026-10-02 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunicationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("WhatsApp", "WhatsApp"),
                            ("Email", "Email"),
                            ("SMS", "SMS"),
                            ("Call", "Call"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("Inbound", "Inbound"), ("Outbound", "Outbound")],
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("agent", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communication_log",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="customers_c_user_id_2c4863_idx",
                    ),
                    models.Index(
                        fields=["channel", "-created_at"],
                        name="customers_c_channel_db6431_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomerNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_customer_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="customers_c_user_id_6bf8ea_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orders_count", models.PositiveIntegerField(default=0)),
                (
                    "total_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("last_order_date", models.DateTimeField(blank=True, null=True)),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("VIP", "VIP"),
                            ("Loyal", "Loyal"),
                            ("New", "New"),
                            ("At Risk", "At Risk"),
                            ("Churned", "Churned"),
                            ("Regular", "Regular"),
                        ],
                        db_index=True,
                        default="Regular",
                        max_length=16,
                    ),
                ),
                (
                    "most_purchased_category",
                    models.CharField(blank=True, max_length=120),
                ),
                ("preferred_payment", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["segment"], name="customers_c_segment_80c201_idx"
                    ),
                    models.Index(
                        fields=["-total_spent"], name="customers_c_total_s_6725f5_idx"
                    ),
                    models.Index(
                        fields=["-last_order_date"],
                        name="customers_c_last_or_6f5a36_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("In Progress", "In Progress"),
                            ("Resolved", "Resolved"),
                            ("Closed", "Closed"),
                        ],
                        db_index=True,
                        default="Open",
                        max_length=16,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                            ("Urgent", "Urgent"),
                        ],
                        db_index=True,
                        default="Medium",
                        max_length=10,
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-opened_at"],
                        name="customers_s_user_id_cbf153_idx",
                    )
                ],
            },
        ),
    ]
