# Generated by Django 6.1.1 on 2026-10-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerprofile",
            name="most_purchased_category",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="preferred_payment",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
